lang: ja

title: GitHub.comの見た目のまま、MarkdownをPagesにするやつ
description: This is a website to test GitHub Pages

lsi: false
safe: true
source: https://github.com/kakudo415/md-pages-test
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge